name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: SwiftLint FlipperZero project
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SwiftLint report
        run: swiftlint lint --reporter github-actions-logging --config "FlipperZero/.swiftlint.yml"
